import boto3
import json
from datetime import datetime

# ============================
# AWS Clients
# ============================
bedrock = boto3.client("bedrock-runtime", region_name="us-east-1")
s3 = boto3.client("s3")
ses = boto3.client("ses", region_name="us-east-1")

# ============================
# Configuration
# ============================
BUCKET_NAME = "codementorai-daily-questions-409513749721"

SENDER_EMAIL = "deepakrajjs2909@gmail.com"
RECIPIENT_EMAIL = "deepakrajjs2909@gmail.com"

MODEL_ID = "amazon.nova-lite-v1:0"


def lambda_handler(event, context):

    prompt = """
You are an expert Software Engineering Interview Coach.

Generate today's coding interview preparation.

Return ONLY in the following format.

Question:
<question>

Difficulty:
<Easy / Medium / Hard>

Hint:
<hint>

Interview Tip:
<tip>

Keep everything under 180 words.
"""

    # ----------------------------
    # Generate AI Response
    # ----------------------------
    response = bedrock.invoke_model(
        modelId=MODEL_ID,
        contentType="application/json",
        accept="application/json",
        body=json.dumps({
            "schemaVersion": "messages-v1",
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "text": prompt
                        }
                    ]
                }
            ],
            "inferenceConfig": {
                "maxTokens": 300,
                "temperature": 0.7
            }
        })
    )

    result = json.loads(response["body"].read())

    ai_text = result["output"]["message"]["content"][0]["text"]

    # ----------------------------
    # Save to S3
    # ----------------------------
    timestamp = datetime.utcnow().strftime("%Y-%m-%d_%H-%M-%S")

    filename = f"question_{timestamp}.json"

    s3.put_object(
        Bucket=BUCKET_NAME,
        Key=filename,
        Body=json.dumps(result, indent=2),
        ContentType="application/json"
    )

    # ----------------------------
    # HTML Email
    # ----------------------------

    today = datetime.utcnow().strftime("%d %B %Y")

    html_body = f"""
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
</head>

<body style="margin:0;padding:0;background:#f4f7fb;font-family:Arial,Helvetica,sans-serif;">

<table width="100%" bgcolor="#f4f7fb" cellpadding="30">

<tr>

<td align="center">

<table width="650" bgcolor="#ffffff"
style="border-radius:15px;
overflow:hidden;
box-shadow:0px 8px 25px rgba(0,0,0,.08);">

<tr>

<td bgcolor="#232F3E"
style="padding:30px;text-align:center;">

<h1 style="color:white;margin:0;">
🚀 CodeMentorAI
</h1>

<p style="color:#D5DBDB;margin-top:8px;">
Your Daily AI Coding Interview Coach
</p>

</td>

</tr>

<tr>

<td style="padding:35px;">

<h2 style="color:#232F3E;">
Hello Deepak 👋
</h2>

<p style="font-size:16px;color:#555;">
Your coding interview question has been generated automatically by your AWS Always-On Agent.
</p>

<table width="100%"
style="margin-top:25px;
background:#F8F9F9;
border-left:6px solid #FF9900;
padding:20px;
border-radius:8px;">

<tr>

<td>

<pre style="white-space:pre-wrap;
font-family:Arial;
font-size:15px;
line-height:1.7;
color:#2C3E50;">{ai_text}</pre>

</td>

</tr>

</table>

<br>

<table width="100%"
style="background:#EEF7FF;
border-radius:10px;
padding:20px;">

<tr>

<td>

<b>📅 Generated On</b><br>
{today}

<br><br>

<b>⚡ Generated By</b><br>
Amazon Bedrock Nova Lite

<br><br>

<b>☁ AWS Services Used</b><br>

• Amazon EventBridge<br>
• AWS Lambda<br>
• Amazon Bedrock<br>
• Amazon S3<br>
• Amazon SES

</td>

</tr>

</table>

<br>

<center>

<a href="https://github.com/"
style="background:#FF9900;
color:white;
padding:14px 28px;
text-decoration:none;
border-radius:8px;
font-weight:bold;">

View Project Repository

</a>

</center>

<hr style="margin-top:40px;">

<p style="font-size:13px;color:#777;text-align:center;">

This email was automatically generated by
<b>CodeMentorAI</b>.

No manual action was required.

Built for the
AWS Build an Always-On Agent Weekend Challenge.

</p>

</td>

</tr>

</table>

</td>

</tr>

</table>

</body>

</html>
"""

    # ----------------------------
    # Send Email
    # ----------------------------

    email_status = "Email sent successfully"

    try:

        ses.send_email(

            Source=SENDER_EMAIL,

            Destination={
                "ToAddresses": [
                    RECIPIENT_EMAIL
                ]
            },

            Message={

                "Subject": {
                    "Data": "🚀 CodeMentorAI | Today's AI Coding Interview Question"
                },

                "Body": {

                    "Html": {
                        "Charset": "UTF-8",
                        "Data": html_body
                    },

                    "Text": {
                        "Charset": "UTF-8",
                        "Data": ai_text
                    }

                }

            }

        )

    except Exception as e:

        email_status = str(e)

    # ----------------------------
    # Lambda Response
    # ----------------------------

    return {

        "statusCode": 200,

        "body": json.dumps({

            "message": "Interview question generated successfully.",

            "email_status": email_status,

            "file": filename,

            "question": ai_text

        })

    }
